### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by AnnaSasDev** [DirectiveAthena/AthenaColor#5]
A better documentation setup than has been previously been provided

**Comment by AnnaSasDev** [comment]
Initialized the ~~[athenacolor.readthedocs.io](https://athenacolor.readthedocs.io/en/latest/)~~ website location. Still needs all the work to be done on this side of that system

**Comment by AnnaSasDev** [comment]
All Directive Athena related project's documentation can be found on: [publish.obsidian.md/directiveathena/.../AthenaColor](https://publish.obsidian.md/directiveathena/Content/Programming/AthenaColor/AthenaColor)
A public git repo is tied to this: [DirectiveAthena/Documentation](https://github.com/DirectiveAthena/Documentation)

**Comment by AnnaSasDev** [comment]
# TODO list:
- [x] InitClass
- [x] Color Systems
    - [x] RGB
    - [x] RGBA
    - [x] HEX
    - [x] HEXA
    - [x] HSV
    - [x] HSL
    - [x] CMYK
- [x] Full list of Html named colors and corresponding RGB codes
- [ ] Color Conversion 
    - [ ] Tuple Conversion
        - [ ] all functions to RGB tuple
        - [ ] all functions to RGBA tuple
        - [ ] all functions to HEX tuple
        - [ ] all functions to HEXA tuple
        - [ ] all functions to HSV tuple
        - [ ] all functions to HSL tuple
        - [ ] all functions to CMYK tuple
    - [ ] Object Conversion
        - [ ] to_RGB
        - [ ] to_RGBA
        - [ ] to_HEX
        - [ ] to_HEXA
        - [ ] to_HSV
        - [ ] to_HSL
        - [ ] to_CMYK
- [ ] Console Styling
    - [ ] Nested Styling
        - [ ] ForeNest
        - [ ] BackNest
        - [ ] StyleNest
    - [ ] Inline Styling
        - [ ] Fore
        - [ ] Back
        - [ ] Style
- [ ] EXAMPLES!!!

**Comment by AnnaSasDev** [comment]
Needs to be completely done form the ground up again
